// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { HookEventName } from "./HookEventName";

export type PluginHookSummary = { key: string, eventName: HookEventName, matcher: string | null, enabled: boolean, statusMessage: string | null, definition: JsonValue, displayOrder: bigint, };
